# HSU Master Configuration with Clean Resource Limits
# All duplicated fields have been consolidated into their respective nested structs

master:
  port: 50055
  
workers:
  - id: "memory-limited-worker"
    type: "managed"
    unit:
      execution:
        executable_path: "./examples/memory-test-app"
        args: ["--consume-memory", "1GB"]
        working_directory: "./examples"
      
      # CLEAN: All resource limits consolidated - no more duplication!
      limits:
        # Process priority (standalone)
        priority: 10
        cpu_shares: 1024  # Linux cgroups weight
        
        # Memory limits (consolidated - no more Memory + MemoryLimits confusion)
        memory:
          max_rss: 512MB          # Replaces old "memory" field
          max_virtual: 1GB        # Virtual memory limit  
          max_swap: 2GB           # Replaces old "memory_swap" field
          warning_threshold: 80.0
          policy: "restart"
          check_interval: 5s
          
        # CPU limits (consolidated - no more CPU + CPULimits confusion)
        cpu:
          max_cores: 2.0          # Replaces old "cpu" field
          max_percent: 75.0       # CPU percentage limit
          max_time: 1h            # Total CPU time limit
          warning_threshold: 70.0
          policy: "throttle"
          check_interval: 10s
          
        # I/O limits (consolidated - no more IOWeight + IOLimits confusion)
        io:
          weight: 100             # Replaces old "io_weight" field
          max_read_bps: 50MB      # Replaces old "io_read_bps" field
          max_write_bps: 30MB     # Replaces old "io_write_bps" field
          max_read_ops: 1000      # Advanced limit
          max_write_ops: 500      # Advanced limit
          warning_threshold: 85.0
          policy: "log"
          check_interval: 30s
          
        # Process limits (consolidated - no more MaxProcesses + ProcessLimits confusion)
        process:
          max_processes: 10         # Replaces old "max_processes" field
          max_file_descriptors: 100 # Replaces old "max_open_files" field
          max_child_processes: 5    # Additional limit
          warning_threshold: 90.0
          policy: "alert"
          check_interval: 15s
          
        # Global monitoring settings
        monitoring:
          enabled: true
          interval: 5s
          history_retention: 1h
          alerting_enabled: true

  - id: "cpu-limited-worker"
    type: "managed"
    unit:
      execution:
        executable_path: "./examples/cpu-test-app"
        args: ["--cpu-intensive"]
      
      # Example: CPU-focused limits
      limits:
        cpu:
          max_percent: 50.0       # Max 50% CPU
          warning_threshold: 80.0
          policy: "graceful_shutdown"
          check_interval: 5s
        monitoring:
          enabled: true
          interval: 2s

  - id: "basic-worker"
    type: "managed"  
    unit:
      execution:
        executable_path: "./examples/basic-app"
      
      # Example: Simple limits (just priority)
      limits:
        priority: 5
        memory:
          max_rss: 256MB
          policy: "log" 