master:
  port: 50055

# ===== LOG COLLECTION CONFIGURATION (OPTIONAL) =====
log_collection:
  enabled: true
  global_aggregation:
    enabled: true
    targets:
      - type: "master_stdout"
        format: "enhanced_plain"
        prefix: "[AGGREGATED]"
      - type: "file" 
        path: "master-aggregated.log"
        format: "enhanced_plain"
  default_worker:
    enabled: true
    capture_stdout: true
    capture_stderr: true
    outputs:
      separate:
        stdout:
          - type: "file"
            path: "{worker_id}-stdout.log"
            format: "enhanced_plain"
        stderr:
          - type: "file"
            path: "{worker_id}-stderr.log"
            format: "enhanced_plain"
          - type: "master_stdout"
            format: "enhanced_plain"
            prefix: "[ERROR]"

workers:
  - id: "test-managed-1"
    type: "managed"
    unit:
      managed:
        metadata:
          name: "Echo gRPC server with logging"
        control:
          execution:
            executable_path: "..\\..\\..\\..\\hsu-example1-go\\cmd\\srv\\echogrpcsrv\\echogrpcsrv.exe"
            args: ["--port", "50051"]
          restart:
            policy: "on-failure"
            max_retries: 3
            retry_delay: "5s"
            backoff_rate: 1.5
          # ===== WORKER-SPECIFIC LOG COLLECTION (OPTIONAL) =====
          log_collection:
            enabled: true
            outputs:
              separate:
                stdout:
                  - type: "file"
                    path: "{worker_id}-detailed.log"
                    format: "enhanced_plain"
        health_check:
          type: "process"
          run_options:
            enabled: true
            interval: "10s"
            timeout: "5s"
            initial_delay: "2s"
            retries: 2
  
  - id: "test-managed-2"
    type: "managed"
    unit:
      managed:
        metadata:
          name: "Echo gRPC server with default logging"
        control:
          execution:
            executable_path: "..\\..\\..\\..\\hsu-example1-go\\cmd\\srv\\echogrpcsrv\\echogrpcsrv.exe"
            args: ["--port", "50052"]
          restart:
            policy: "on-failure"
            max_retries: 3
            retry_delay: "5s"
            backoff_rate: 1.5
          # No log_collection section = uses defaults
        health_check:
          type: "process"
          run_options:
            enabled: true
            interval: "10s"
            timeout: "5s"
            initial_delay: "2s"
            retries: 2 